on gametest:
    set {branch} to 2
    if {branch} is 1:
        set test block at 0 1 0 to diamond_block
    else if {branch} is 2:
        set test block at 0 1 0 to gold_block
    else:
        set test block at 0 1 0 to emerald_block

    set {branch} to 3
    if {branch} is 1:
        set test block at 1 1 0 to diamond_block
    else if {branch} is 2:
        set test block at 1 1 0 to gold_block
    else:
        set test block at 1 1 0 to emerald_block
