on gametest projectile context:
    add 2 to arrow knockback strength of event-entity
    set arrow pierce level of event-entity to 3

on gametest explosive entity context:
    set explosive yield of event-entity to 5

on break of item frame:
    set test name of entity hanging entity to "hanging entity"
    set test name of entity hanging remover to "hanging remover"

on block fertilize:
    set test block above fertilized blocks to gold_block
